In [30]:
import pandas as pd
bios = pd.read_csv('./data/bios.csv')
coffee = pd.read_csv('./warmup-data/coffee.csv')

In [6]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [13]:
import numpy as np
coffee['Price'] = np.where(coffee['Coffee Type'] == 'Espresso', 6, 10)

In [14]:
coffee['Revenue'] = coffee['Price'] * coffee['Units Sold']

In [ ]:
coffee

In [27]:
coffee['yesterday_revenue'] = coffee['Revenue'].shift(2)

In [28]:
coffee['revenue_pct_change'] = coffee["Revenue"] / coffee['yesterday_revenue'] * 100

In [29]:
coffee

,Day,Coffee Type,Units Sold,Price,Revenue,yesterday_revenue,revenue_pct_change
0,Monday,Espresso,25,6,150,NaN,NaN
1,Monday,Latte,15,10,150,NaN,NaN
2,Tuesday,Espresso,30,6,180,150.0,120.000000
3,Tuesday,Latte,20,10,200,150.0,133.333333
4,Wednesday,Espresso,35,6,210,180.0,116.666667
5,Wednesday,Latte,25,10,250,200.0,125.000000
6,Thursday,Espresso,40,6,240,210.0,114.285714
7,Thursday,Latte,30,10,300,250.0,120.000000
8,Friday,Espresso,45,6,270,240.0,112.500000
9,Friday,Latte,35,10,350,300.0,116.666667
10,Saturday,Espresso,45,6,270,270.0,100.000000
11,Saturday,Latte,35,10,350,350.0,100.000000
12,Sunday,Espresso,45,6,270,270.0,100.000000
13,Sunday,Latte,35,10,350,350.0,100.000000

In [42]:
bios = bios.dropna(subset=["height_cm"])
bios['height_rank'] = bios['height_cm'].rank(ascending=False)

In [43]:
bios.sort_values(['height_rank'])

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_rank
89070,89782,Yao Ming,1980-09-12,Xuhui District,Shanghai,CHN,People's Republic of China,226.0,141.0,NaN,1.0
6978,7013,Arvydas Sabonis,1964-12-19,Kaunas,Kaunas,LTU,Lithuania Soviet Union,223.0,122.0,NaN,2.5
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN,2.5
5673,5696,Gunther Behnke,1963-01-19,Leverkusen,Nordrhein-Westfalen,GER,Germany,221.0,114.0,NaN,5.0
89075,89787,Roberto Dueñas,1975-11-01,Madrid,Madrid,ESP,Spain,221.0,137.0,NaN,5.0
...,...,...,...,...,...,...,...,...,...,...,...
4664,4681,Salvador Miranda,1949-09-13,NaN,NaN,NaN,Nicaragua,130.0,51.0,NaN,106647.5
4517,4532,Boston Simbeye,1959-12-24,NaN,NaN,NaN,Malawi,130.0,67.0,NaN,106647.5
4516,4531,Helman Palije,1967-06-24,NaN,NaN,NaN,Malawi,128.0,74.0,NaN,106649.0
28619,28832,Rosario Briones,1953-10-05,San Luis Potosí,San Luis Potosí,MEX,Mexico,127.0,42.0,NaN,106650.5
4515,4530,Lyton Mphande,1963-05-14,NaN,NaN,NaN,Malawi,127.0,62.0,NaN,106650.5