In [2]:
import pandas as pd
coffee = pd.read_csv("./warmup-data/coffee.csv")

In [5]:
import numpy as np
coffee['Price'] = np.where(coffee['Coffee Type'] == 'Espresso', 10, 6)

In [6]:
coffee.groupby(['Coffee Type'])['Units Sold'].mean()

Coffee Type
Espresso    37.857143
Latte       27.857143
Name: Units Sold, dtype: float64

In [7]:
coffee.groupby(['Coffee Type']).agg({'Units Sold': 'sum', 'Price': 'sum'})

             Units Sold  Price
Coffee Type
Espresso            265     70
Latte               195     42

In [8]:
coffee

          Day Coffee Type  Units Sold  Price
0      Monday    Espresso          25     10
1      Monday       Latte          15      6
2     Tuesday    Espresso          30     10
3     Tuesday       Latte          20      6
4   Wednesday    Espresso          35     10
5   Wednesday       Latte          25      6
6    Thursday    Espresso          40     10
7    Thursday       Latte          30      6
8      Friday    Espresso          45     10
9      Friday       Latte          35      6
10   Saturday    Espresso          45     10
11   Saturday       Latte          35      6
12     Sunday    Espresso          45     10
13     Sunday       Latte          35      6